appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AQtEA9lXou9Pbu3n6oBHL6OP42+gUevMmh6PblJFYtuN/mmwhwLTKDtomXOjoc6CBjPELxjSvvNC6BYHXcGaFaDX3QTL4b3KOlr9zdLgi5lE+rZUo3UGiAhlzUhpCXVe2GX6wcM83cWob0T3LwMhkRo6r3vPNhfAEVN/AqJt0jA+GYggKLgot2UnUpwTGntU+7AWxZMrjoXUO4a2dVH2AvfgZvCtQapI0TJjnfgd+n3SAFHa7JHWjJHsCcjLLxNxzTmlt5PbaAiN0LdiaOCn2GDx8sHfS9HCBzlhTH0OCSyhyKHxhi2JUPaz/JIDhIQvvumg6eFRWT+mN4UUF3OOXBQbamY3FtA29imYUOH480OIOkPpL++5FjZQoR+aZmhssis7D0m+OfDyGZeOjLhiBeo6KMvoVxzidezNN3V5drRvu1xcxpOUtZ3hFqwJka7W3cQ0YAP4TBBbFz8Dlfm3aT9iRC07cnZvSQULN0pTOc12S1CzqNCGcyCrMCKQ+fL92D8Uy623mzkZeVzTk9GfgAbkhIrQ1CbUYfFCu2suqJe4kWXIYZc1D74n9ZBwOWtLxNwaXzTRrGtHB7eM/FKIJHGpoSEohD4409ULNvB3u3ihaKBQulMqxmqhNPemiyjcSCQjbo6ipLW9qP7BxbBh0Zi91//YB7WEi09VyAmCTtE=}
